apiVersion: apps/v1
kind: Deployment
metadata:
  name: jdbc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jdbc-app
  template:
    metadata:
      labels:
        app: jdbc-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port:   "8080"
        prometheus.io/path:   "/actuator/prometheus"
    spec:
      containers:
        - name: jdbc-app
          image: spring-jdbc-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: pg-postgresql.default.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: mydatabase
            - name: DB_USER
              value: myuser
            - name: DB_PASS
              value: mypassword
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu:    100m
              memory: 256Mi
            limits:
              cpu:    500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: jdbc-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path:   "/actuator/prometheus"
    prometheus.io/port:   "8080"
spec:
  selector:
    app: jdbc-app
  ports:
    - port: 8080
      targetPort: 8080