apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: db
    db: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      db: mysql
  template:
    metadata:
      labels:
        app: db
        db: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.1   # przykładowa wersja MySQL
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: examplepass
            - name: MYSQL_DATABASE
              value: exampledb
            - name: MYSQL_USER
              value: exampleuser
            - name: MYSQL_PASSWORD
              value: examplepass
          ports:
            - containerPort: 3306
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: db
    db: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    app: db
    db: mysql