# Service dla Prometheusa (ClusterIP, aby umożliwić dostęp w klastrze lub via NodePort/LoadBalancer jeśli potrzebne)
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  # namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus